Fix multi-dim array unit conversion with unit.convert(...)
In the ctypes implementation we used to get the raw array data pointer and pass that through, now we are going through Cython and hence the errors seen in #97:

```
======================================================================
ERROR: test_circular_subset (iris.tests.experimental.regrid.test_regrid_area_weighted_rectilinear_src_and_grid.TestAreaWeightedRegrid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "iris/tests/experimental/regrid/test_regrid_area_weighted_rectilinear_src_and_grid.py", line 532, in test_circular_subset
    res = regrid_area_weighted(src, dest)
  File "iris/experimental/regrid.py", line 722, in regrid_area_weighted_rectilinear_src_and_grid
    src_x_bounds = _get_bounds_in_units(src_x, x_units, dtype)
  File "iris/experimental/regrid.py", line 349, in _get_bounds_in_units
    return coord.units.convert(coord.bounds.astype(dtype), units).astype(dtype)
  File "cf_units/__init__.py", line 1840, in convert
    _cv_convert_array[ctype](ut_converter, result, result)
  File "cf_units/_udunits2.pyx", line 308, in cf_units._udunits2.convert_doubles
    def convert_doubles(Converter converter, np.ndarray[np.float64_t] in_, np.ndarray[np.float64_t] out):
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
```

Also addresses the issue of inplace non-native byte ordered conversion (with a ValueError).

Closes #97. Replaces #98.